source 'https://rubygems.org'

#gem "octopress-solarized", path: "../../solarized"
#gem "jekyll", path: "../../jekyll"

gemspec path: '../'
group :jekyll_plugins do
end
#gem "octopress", path: "../../cli"
#gem 'octopress-escape-code', path: "../../escape-code"
#gem "octopress-ink", path: "../../ink"
#gem "octopress-codefence", path: "../../codefence"
